user_resetting_request:
    path:     /request
    defaults: { _controller: "UniUserBundle:Resetting:request" }
    methods: [GET]
user_resetting_send_email:
    path:     /send-email
    defaults: { _controller: "UniUserBundle:Resetting:sendEmail" }
    methods: [POST]
user_resetting_check_email:
    path:     /check-email
    defaults: { _controller: "UniUserBundle:Resetting:checkEmail" }
    methods: [GET]
user_resetting_reset:
    path:     /reset/{token}
    defaults: { _controller: "UniUserBundle:Resetting:reset" }
    methods: [GET|POST]
