Uni\AdminBundle\Entity\Member:
    type: entity
    table: Member
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: '200'
        lastname:
            type: string
            length: '200'
            nullable: true
        email:
            type: string
            length: '100'
            nullable: true
        phonenumber:
            type: string
            length: '100'
            nullable: true
        birthdate:
            type: date
            nullable: true
        admissiondate:
            type: date
            nullable: true
        active:
            type: boolean
            options:
                default: true
        path:
            type: string
            length: '300'
            nullable: true
        file:
            type: string
            length: '300'
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    manyToOne:
        role:
            targetEntity: MemberRole
            inversedBy: member
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
