Uni\AdminBundle\Entity\Report:
    type: entity
    table: Report
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '200'
        content:
            type: text
            nullable: true
        published:
            type: boolean
            options:
                default: false
        path:
            type: string
            length: '300'
            nullable: true
        file:
            type: string
            length: '300'
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }