framework:
    #esi:             ~
    translator:      { fallbacks: [es] }
    default_locale: %locale%
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    #validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    validation:      { enabled: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  es
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

