services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    uniuser.mailer:
        class: Uni\UserBundle\Mailer\Mailer
        arguments:
            0: "@mailer"
            1: "@router"
            2: "@templating"
            3:
                confirmation.template: %fos_user.registration.confirmation.template%
                resetting.template: %fos_user.resetting.email.template%
                from_email:
                    confirmation: %fos_user.registration.confirmation.from_email%
                    resetting: %fos_user.resetting.email.from_email%
    #uniuserbundle.form.profile:
    #    class: Uni\UserBundle\Form\ProfileType
    #    tags:
    #        - { name: form.type, alias: uni_userbundle_user_profile }