notice:
    path:     /
    defaults: { _controller: "UniAdminBundle:Notice:index" }
    methods: [GET]

notice_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Notice:show" }

notice_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Notice:new" }

notice_create:
    path:     /create
    defaults: { _controller: "UniAdminBundle:Notice:create" }
    methods: [POST]

notice_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Notice:edit" }

notice_update:
    path:     /{id}/update
    defaults: { _controller: "UniAdminBundle:Notice:update" }
    methods: [POST|PUT]

notice_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Notice:delete" }
    methods: [POST|DELETE]
