productcategory:
    path:     /
    defaults: { _controller: "UniAdminBundle:ProductCategory:index" }
    methods: [GET]

productcategory_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:ProductCategory:show" }

productcategory_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:ProductCategory:new" }

productcategory_create:
    path:     /create
    defaults: { _controller: "UniAdminBundle:ProductCategory:create" }
    methods: [POST]

productcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:ProductCategory:edit" }

productcategory_update:
    path:     /{id}/update
    defaults: { _controller: "UniAdminBundle:ProductCategory:update" }
    methods: [POST|PUT]

productcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:ProductCategory:delete" }
    methods: [POST|DELETE]
