product:
    path:     /
    defaults: { _controller: "UniAdminBundle:Product:index" }
    methods: [GET]

product_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Product:show" }

product_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Product:new" }

product_create:
    path:     /create
    defaults: { _controller: "UniAdminBundle:Product:create" }
    methods: [POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Product:edit" }

product_update:
    path:     /{id}/update
    defaults: { _controller: "UniAdminBundle:Product:update" }
    methods: [POST|PUT]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Product:delete" }
    methods: [POST|DELETE]
