service:
    path:     /
    defaults: { _controller: "UniAdminBundle:Service:index" }
    methods: [GET]

service_show:
    path:     /{id}/show
    defaults: { _controller: "UniAdminBundle:Service:show" }

service_new:
    path:     /new
    defaults: { _controller: "UniAdminBundle:Service:new" }

service_create:
    path:     /create
    defaults: { _controller: "UniAdminBundle:Service:create" }
    methods: [POST]

service_edit:
    path:     /{id}/edit
    defaults: { _controller: "UniAdminBundle:Service:edit" }

service_update:
    path:     /{id}/update
    defaults: { _controller: "UniAdminBundle:Service:update" }
    methods: [POST|PUT]

service_delete:
    path:     /{id}/delete
    defaults: { _controller: "UniAdminBundle:Service:delete" }
    methods: [POST|DELETE]
